#include <stdio.h>
#include <stdlib.h>
#include <mpfr.h>
#include <pthread.h>
#include <time.h>
// High Precision Pi Digit Calculator
// Code mostly generated by ChatGPT
mpfr_t pi;
mpfr_t term;
mpfr_t sum;

pthread_mutex_t mutex = PTHREAD_MUTEX_INITIALIZER;
int current_iteration = 0;
int iterations_per_thread;

long long current_timestamp() {
    //This is a linux solution and it may or may not work on Windows 10/11. It should work on Mac.
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return (long long)ts.tv_sec * 1000000000 + ts.tv_nsec;
}

void* calculate_pi(void* arg) {
    int thread_id = *(int*)arg;
    mpfr_t temp;
    mpfr_init(temp);
    for (int i = 0; i < iterations_per_thread; ++i) {
        /*
            -This code can calculate millions of digits of pi
            -It is recommended to use multiple cores for precision of above ~100 000
            -It may take several minutes and above to calculate more than a million digits 
        */
        pthread_mutex_lock(&mutex);
        int current = current_iteration++;
        pthread_mutex_unlock(&mutex);

        mpfr_set_si(term, 1, MPFR_RNDN);
        mpfr_div_si(term, term, 2 * current + 1, MPFR_RNDN);

        if (current % 2 == 0) {
            mpfr_add(sum, sum, term, MPFR_RNDN);
        } else {
            mpfr_sub(sum, sum, term, MPFR_RNDN);
        }
    }

    mpfr_mul(temp, sum, pi, MPFR_RNDN);
    mpfr_swap(sum, temp);

    mpfr_clear(temp);

    return NULL;
}

int main() {
    int PRECISION, THREAD_COUNT;
    //precision is not the amount of digits
    printf("Enter precision: ");
    scanf("%d", &PRECISION);
    printf("Enter Thread count: ");
    scanf("%d", &THREAD_COUNT);

    mpfr_init2(pi, PRECISION);
    mpfr_init2(term, PRECISION);
    mpfr_init2(sum, PRECISION);

    mpfr_const_pi(pi, MPFR_RNDN);

    int thread_ids[THREAD_COUNT];
    pthread_t threads[THREAD_COUNT];

    iterations_per_thread = PRECISION / THREAD_COUNT;

    long long start_time = current_timestamp();

    for (int i = 0; i < THREAD_COUNT; ++i) {
        thread_ids[i] = i;
        pthread_create(&threads[i], NULL, calculate_pi, &thread_ids[i]);
    }

    for (int i = 0; i < THREAD_COUNT; ++i) {
        pthread_join(threads[i], NULL);
    }

    long long end_time = current_timestamp();
    double elapsed_time = (end_time - start_time) / 1e9;

    printf("Time taken: %f seconds\n", elapsed_time);

    FILE* file = fopen("pi_digits.txt", "w");
    mpfr_exp_t exponent;
    char* str = mpfr_get_str(NULL, &exponent, 10, 0, pi, MPFR_RNDN);
    fprintf(file, "3.%s\n", str + 1);
    free(str);
    fclose(file);

    mpfr_clear(pi);
    mpfr_clear(term);
    mpfr_clear(sum);

    return 0;
}

